import type { FastifyInstance } from "fastify";
import { forgotPasswordSchema, loginSchema, publicRegistrationSchema, refreshSchema, resetPasswordSchema, updateProfileSchema } from "@redvital/domain";
import { z } from "zod";
import { AuthError, AuthService, publicUser } from "./service.js";
import { authenticate, requireRoles } from "./guards.js";
import type { AuthStore } from "./types.js";
import type { Environment } from "../config.js";

const parse = <T>(schema: z.ZodType<T, z.ZodTypeDef, unknown>, value: unknown): T => { const result = schema.safeParse(value); if (!result.success) throw new AuthError(400, "Invalid request"); return result.data; };
const errorResponse = { type: "object", required: ["message"], properties: { message: { type: "string" } } };
const userResponse = { type: "object", required: ["id", "email", "role", "status"], properties: { id: { type: "string", format: "uuid" }, email: { type: "string", format: "email" }, role: { type: "string", enum: ["donor", "patient", "admin"] }, status: { type: "string", enum: ["active", "disabled"] } } };
const profileResponse = { type: ["object", "null"], properties: { firstName: { type: "string" }, lastName: { type: "string" }, phone: { type: ["string", "null"] }, bloodType: { type: "string", enum: ["O", "A", "B", "AB"] }, rhFactor: { type: "string", enum: ["+", "-"] }, city: { type: "string" }, available: { type: "boolean" } } };
const sessionResponse = { type: "object", required: ["user"], properties: { user: userResponse, accessToken: { type: "string" }, refreshToken: { type: "string" } } };
const authSecurity: { [securityLabel: string]: readonly string[] }[] = [{ bearerAuth: [] }, { accessCookie: [] }];
const cookieOptions = (env: Environment) => ({ httpOnly: true, secure: env.NODE_ENV === "production", sameSite: "lax" as const, path: "/", maxAge: 60 * 60 * 24 * 30 });
const accessCookieOptions = (env: Environment) => ({ httpOnly: true, secure: env.NODE_ENV === "production", sameSite: "lax" as const, path: "/", maxAge: 60 * 15 });

export async function authRoutes(app: FastifyInstance, options: { store: AuthStore; environment: Environment; passwordResetNotifier?: (token: string) => Promise<void> }) {
  const service = new AuthService(options.store, options.environment, options.passwordResetNotifier);
  const readRefresh = (request: any, body: { refreshToken?: string }) => body.refreshToken ?? request.cookies[options.environment.AUTH_COOKIE_NAME];
  const sessionReply = (reply: any, session: any, client: "web" | "mobile") => { if (client === "web") { reply.setCookie(options.environment.AUTH_COOKIE_NAME, session.refreshToken, cookieOptions(options.environment)); reply.setCookie(options.environment.AUTH_ACCESS_COOKIE_NAME, session.accessToken, accessCookieOptions(options.environment)); return { user: session.user }; } return session; };
  const commonErrors = { 400: errorResponse, 401: errorResponse, 409: errorResponse };

  app.post("/auth/register", { schema: { tags: ["auth"], summary: "Registro público de donante o paciente", body: { type: "object", required: ["firstName", "lastName", "email", "password", "phone", "bloodType", "rhFactor", "city", "role"], properties: { firstName: { type: "string" }, lastName: { type: "string" }, email: { type: "string", format: "email" }, password: { type: "string", format: "password" }, phone: { type: "string" }, bloodType: { type: "string", enum: ["O", "A", "B", "AB"] }, rhFactor: { type: "string", enum: ["+", "-"] }, city: { type: "string" }, role: { type: "string", enum: ["donor", "patient"] }, available: { type: "boolean" } } }, response: { 201: userResponse, ...commonErrors } } }, async (request, reply) => reply.code(201).send(await service.register(parse(publicRegistrationSchema, request.body))));
  app.post("/auth/login", { schema: { tags: ["auth"], summary: "Inicio de sesión", body: { type: "object", required: ["email", "password"], properties: { email: { type: "string", format: "email" }, password: { type: "string", format: "password" }, client: { type: "string", enum: ["web", "mobile"], default: "web" } } }, response: { 200: sessionResponse, ...commonErrors } } }, async (request, reply) => { const input = parse(loginSchema, request.body); return sessionReply(reply, await service.login(input.email, input.password), input.client); });
  app.post("/auth/refresh", { schema: { tags: ["auth"], summary: "Rotación de refresh token", body: { type: "object", properties: { refreshToken: { type: "string" }, client: { type: "string", enum: ["web", "mobile"], default: "web" } } }, response: { 200: sessionResponse, ...commonErrors } } }, async (request, reply) => { const input = parse(refreshSchema, request.body ?? {}); const token = readRefresh(request, input); if (!token) throw new AuthError(401, "Invalid refresh token"); return sessionReply(reply, await service.refresh(token), input.client); });
  app.post("/auth/logout", { schema: { tags: ["auth"], summary: "Revoca el refresh token actual", body: { type: "object", properties: { refreshToken: { type: "string" }, client: { type: "string", enum: ["web", "mobile"], default: "web" } } }, response: { 204: { type: "null" } } } }, async (request, reply) => { const input = parse(refreshSchema, request.body ?? {}); const token = readRefresh(request, input); if (token) await service.logout(token); reply.clearCookie(options.environment.AUTH_COOKIE_NAME, { path: "/" }); reply.clearCookie(options.environment.AUTH_ACCESS_COOKIE_NAME, { path: "/" }); return reply.code(204).send(); });
  app.post("/auth/forgot-password", { schema: { tags: ["auth"], summary: "Solicita restablecimiento sin enumerar usuarios", body: { type: "object", required: ["email"], properties: { email: { type: "string", format: "email" } } }, response: { 202: { type: "object", properties: { message: { type: "string" } } }, 400: errorResponse } } }, async (request, reply) => { await service.forgotPassword(parse(forgotPasswordSchema, request.body).email); return reply.code(202).send({ message: "If the account exists, recovery instructions will be sent." }); });
  app.post("/auth/reset-password", { schema: { tags: ["auth"], summary: "Restablece contraseña usando token temporal de único uso", body: { type: "object", required: ["token", "password"], properties: { token: { type: "string" }, password: { type: "string", format: "password" } } }, response: { 204: { type: "null" }, 400: errorResponse } } }, async (request, reply) => { const input = parse(resetPasswordSchema, request.body); await service.resetPassword(input.token, input.password); return reply.code(204).send(); });
  const auth = authenticate(options.store, options.environment);
  app.get("/users/me", { preHandler: auth, schema: { tags: ["users"], summary: "Usuario autenticado", security: authSecurity, response: { 200: userResponse, 401: errorResponse } } }, async (request) => publicUser(request.authUser!));
  app.get("/users/me/profile", { preHandler: auth, schema: { tags: ["users"], summary: "Perfil autenticado", security: authSecurity, response: { 200: profileResponse, 401: errorResponse } } }, async (request) => request.authUser!.profile);
  app.patch("/users/me/profile", { preHandler: auth, schema: { tags: ["users"], summary: "Actualiza perfil propio", security: authSecurity, body: { type: "object" }, response: { 200: profileResponse, 400: errorResponse, 401: errorResponse } } }, async (request) => { const updated = await options.store.updateProfile(request.authUser!.id, parse(updateProfileSchema, request.body)); await options.store.audit("USER_PROFILE_UPDATED", "User", updated.id, updated.id); return updated.profile; });
  app.patch("/users/me/availability", { preHandler: auth, schema: { tags: ["users"], summary: "Actualiza disponibilidad propia", security: authSecurity, body: { type: "object", required: ["available"], properties: { available: { type: "boolean" } } }, response: { 200: profileResponse, 400: errorResponse, 401: errorResponse } } }, async (request) => { const body = parse(z.object({ available: z.boolean() }), request.body); const updated = await options.store.updateProfile(request.authUser!.id, { available: body.available }); await options.store.audit("USER_AVAILABILITY_UPDATED", "User", updated.id, updated.id); return updated.profile; });
  app.get("/admin/users", { preHandler: [auth, requireRoles("admin")], schema: { tags: ["admin"], summary: "Listado administrativo de usuarios", security: authSecurity, response: { 200: { type: "array", items: userResponse }, 401: errorResponse, 403: errorResponse } } }, async () => (await options.store.listUsers()).map(publicUser));
}
