import { describe, expect, it, vi } from "vitest";
vi.mock("argon2", () => ({ default: { argon2id: 2, hash: async (value: string) => `test-argon2id-${value}`, verify: async (encoded: string, value: string) => encoded === `test-argon2id-${value}` }, argon2id: 2 }));
import { buildApp } from "../src/app.ts";
import type { Environment } from "../src/config.js";
import { MemoryStore } from "./memory-store.mjs";
import { hashToken } from "../src/auth/crypto.js";

const env: Environment = { NODE_ENV: "test", API_HOST: "127.0.0.1", API_PORT: 0, DATABASE_URL: "postgresql://test:test@localhost:5432/test", CORS_ORIGIN: "http://localhost:8000", AUTH_ACCESS_TOKEN_SECRET: "a".repeat(40), AUTH_REFRESH_TOKEN_SECRET: "b".repeat(40), AUTH_ACCESS_TOKEN_TTL: "15m", AUTH_REFRESH_TOKEN_TTL: "30d", AUTH_PASSWORD_RESET_TTL: "1h", AUTH_COOKIE_NAME: "rv_test", AUTH_ACCESS_COOKIE_NAME: "rv_access_test" };
const registration = { firstName: "Sofía", lastName: "Demo", email: "SOFIA@EXAMPLE.COM", password: "Demo1234", phone: "54911000000", bloodType: "O", rhFactor: "+", city: "Córdoba", role: "donor", available: true };
async function setup() { const store = new MemoryStore(); const app = await buildApp(env, store); return { app, store }; }
describe("authentication", () => {
  it("registers normalized valid users and rejects duplicate, weak password and public admins", async () => { const { app } = await setup(); expect((await app.inject({ method: "POST", url: "/auth/register", payload: registration })).statusCode).toBe(201); expect((await app.inject({ method: "POST", url: "/auth/register", payload: registration })).statusCode).toBe(409); expect((await app.inject({ method: "POST", url: "/auth/register", payload: { ...registration, email: "x@example.com", password: "weak" } })).statusCode).toBe(400); expect((await app.inject({ method: "POST", url: "/auth/register", payload: { ...registration, email: "a@example.com", role: "admin" } })).statusCode).toBe(400); await app.close(); });
  it("logs in, rotates refresh tokens and logs out", async () => { const { app } = await setup(); await app.inject({ method: "POST", url: "/auth/register", payload: registration }); const login = await app.inject({ method: "POST", url: "/auth/login", payload: { email: "sofia@example.com", password: "Demo1234", client: "mobile" } }); expect(login.statusCode).toBe(200); const session = login.json(); expect((await app.inject({ method: "POST", url: "/auth/refresh", payload: { refreshToken: session.refreshToken, client: "mobile" } })).statusCode).toBe(200); expect((await app.inject({ method: "POST", url: "/auth/refresh", payload: { refreshToken: session.refreshToken, client: "mobile" } })).statusCode).toBe(401); const next = (await app.inject({ method: "POST", url: "/auth/login", payload: { email: "sofia@example.com", password: "Demo1234", client: "mobile" } })).json(); expect((await app.inject({ method: "POST", url: "/auth/logout", payload: { refreshToken: next.refreshToken, client: "mobile" } })).statusCode).toBe(204); expect((await app.inject({ method: "POST", url: "/auth/refresh", payload: { refreshToken: next.refreshToken, client: "mobile" } })).statusCode).toBe(401); await app.close(); });
  it("rejects inactive users", async () => { const { app, store } = await setup(); await app.inject({ method: "POST", url: "/auth/register", payload: registration }); (await store.findUserByEmail("sofia@example.com"))!.status = "disabled"; expect((await app.inject({ method: "POST", url: "/auth/login", payload: { email: "sofia@example.com", password: "Demo1234" } })).statusCode).toBe(401); await app.close(); });
  it("does not reveal login or recovery account existence, and resets once", async () => { let received = ""; const store = new MemoryStore(); const app = await buildApp(env, store); await app.inject({ method: "POST", url: "/auth/register", payload: registration }); expect((await app.inject({ method: "POST", url: "/auth/login", payload: { email: "none@example.com", password: "Demo1234" } })).statusCode).toBe(401); expect((await app.inject({ method: "POST", url: "/auth/login", payload: { email: "sofia@example.com", password: "wrong" } })).statusCode).toBe(401); const direct = await import("../src/auth/service.js"); const service = new direct.AuthService(store, env, async (token) => { received = token; }); await service.forgotPassword("sofia@example.com"); await service.resetPassword(received, "Nueva1234"); await expect(service.resetPassword(received, "Otra1234")).rejects.toMatchObject({ statusCode: 400 }); await app.close(); });
  it("rejects expired password reset tokens", async () => { const { store, app } = await setup(); await app.inject({ method: "POST", url: "/auth/register", payload: registration }); const user = await store.findUserByEmail("sofia@example.com"); await store.createPasswordResetToken(user!.id, hashToken("x".repeat(48)), new Date(Date.now() - 1)); const { AuthService } = await import("../src/auth/service.js"); await expect(new AuthService(store, env).resetPassword("x".repeat(48), "Nueva1234")).rejects.toMatchObject({ statusCode: 400 }); await app.close(); });
  it("enforces roles and only exposes the authenticated user", async () => { const { app, store } = await setup(); await app.inject({ method: "POST", url: "/auth/register", payload: registration }); const donor = (await app.inject({ method: "POST", url: "/auth/login", payload: { email: "sofia@example.com", password: "Demo1234", client: "mobile" } })).json(); const patient = (await app.inject({ method: "POST", url: "/auth/register", payload: { ...registration, email: "paciente@example.com", role: "patient" } })).json(); const patientToken = (await app.inject({ method: "POST", url: "/auth/login", payload: { email: patient.email, password: "Demo1234", client: "mobile" } })).json().accessToken; const admin = await store.createUser({ email: "admin@example.com", passwordHash: null, role: "admin", profile: { firstName: "Ana", lastName: "Admin", phone: null, bloodType: "A", rhFactor: "+", city: "Córdoba", available: false } }); const { createAccessToken } = await import("../src/auth/tokens.js"); const adminToken = await createAccessToken(admin, env); expect((await app.inject({ method: "GET", url: "/admin/users", headers: { authorization: `Bearer ${donor.accessToken}` } })).statusCode).toBe(403); expect((await app.inject({ method: "GET", url: "/admin/users", headers: { authorization: `Bearer ${patientToken}` } })).statusCode).toBe(403); expect((await app.inject({ method: "GET", url: "/admin/users", headers: { authorization: `Bearer ${adminToken}` } })).statusCode).toBe(200); expect((await app.inject({ method: "GET", url: "/users/me", headers: { authorization: `Bearer ${donor.accessToken}` } })).json().email).toBe("sofia@example.com"); await app.close(); });
});
